services:
  - type: web
    name: noteshub-backend
    env: node
    plan: free
    buildCommand: chmod +x build-simple.sh && ./build-simple.sh
    startCommand: chmod +x start-simple.sh && ./start-simple.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
