services:
  - type: web
    name: noteshub-api
    env: node
    plan: free
    buildCommand: chmod +x build-simple.sh && ./build-simple.sh
    startCommand: chmod +x start-simple.sh && ./start-simple.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: PGHOST
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGPORT
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: FORCE_SECURE_COOKIES
        value: true
      - key: FORCE_HSTS
        value: true
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
    autoDeploy: true
