services:
  - type: web
    name: noteshub-backend
    env: node
    buildCommand: chmod +x build-render.sh && ./build-render.sh
    startCommand: chmod +x start-render.sh && ./start-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FORCE_SECURE_COOKIES
        value: true
      - key: FORCE_HSTS
        value: true
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false