services:
  # Backend API service
  - type: web
    name: noteshub-api
    env: node
    plan: free
    buildCommand: ./build.sh
    startCommand: npm start
    healthCheckPath: /api/test
    healthCheckTimeout: 30
    healthCheckRoutes:
      - route: /api/ping
      - route: /api/cors-test
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: PGHOST
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGPORT
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: FORCE_SECURE_COOKIES
        value: true
      - key: FORCE_HSTS
        value: true
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://notezhubz.web.app,https://notezhubz.firebaseapp.com,https://noteshub-ocpi.onrender.com"
      - key: CORS_ALLOW_CREDENTIALS
        value: "true"
    autoDeploy: true
