app = "notezhub-server"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

[vm]
  memory = 256
  cpu_kind = "shared"
  cpus = 1
